######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 23 20:03:28 2014
######################################################################

TEMPLATE = subdirs
CONFIG += ordered

SUBDIRS += extern/cxcore
SUBDIRS += src

